version: "3.9"
services:
  db:
    image: mariadb:10.7
    container_name: nestjs-social-media-db
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - ./database/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: socialmedia
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    networks:
      - nestjssocialmedia
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:5.1.1
    ports:
      - "8088:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - nestjssocialmedia
networks:
  nestjssocialmedia:
